name: 🪲 Bug Report
description: Submit a bug report
title: "Bug: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank for your report!
        We appreciate your help and will do our best to resolve the issue as soon as we can!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Traceback output
      description: If you got a traceback screen with error details, press 'copy' and paste its content here.
      render: shell
  - type: input
    id: submod-version
    attributes:
      label: Submod version
      description: What version of the submod do you have?
    validations:
      required: true
  - type: input
    id: mas-version
    attributes:
      label: Monika After Story version
      description: What version of Monika After Story do you have?
    validations:
      required: true
  - type: dropdown
    id: mas-unstable
    attributes:
      label: Unstable
      description: Are you running unstable version of MAS?
      options:
        - "Yes"
        - "No"
        - Unsure
    validations:
      required: true
