name: 🙋 Help Request
description: Submit a request for help and support about this submod
title: "Help: "
labels: [ "question" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reaching out!
        We'll respond to your request as soon as we can and will do our best to help you!
  - type: textarea
    id: question
    attributes:
      label: What do you need our help with?
      description: Please tell us what is concerning you about this mod or what do you want to know.
      placeholder: I was wondering if something happens if I do X, so I wanted to make it clear...
    validations:
      required: true
