#!/bin/sh
set -e

scripts/_util/try-install-env.sh

echo "# Store submod version in an environment variable"
export VERSION="$(.github/scripts/extract-version.sh)"

echo "# Compile submod and verify spritepacks"
.github/scripts/compile-submod.sh

echo "# Package submod"
(cd build/out; find game | zip -q "msh-mod-$VERSION.zip" -9 -@)
rm -r build/out/game

echo "# Package spritepacks"
.github/scripts/package-spritepacks.sh
