#!/bin/sh
if ! git diff --staged --name-only | perl -ne 'exit 1 unless /\.rpyc?$/'; then exit 0; fi

echo "*** .rpy/.rpyc files changed, linting before commit. ***"
if ! { scripts/lint; exit_code="$?"; (exit "$exit_code"; ); }; then
    echo "*** Lint failed, refusing to commit! ***"
    exit "$exit_code"
else
    echo "*** Lint successful, committing. ***"
fi
